# Generated by Django 4.0.6 on 2022-11-26 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DosageForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ROI', models.CharField(choices=[('Oral', 'Oral'), ('Insufflated', 'Insufflated'), ('Vaporized', 'Vaporized'), ('Rectal', 'Rectal'), ('Intravenous', 'Intravenous')], default='Oral', max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Dosage Forms',
                'db_table': 'dosage_forms',
            },
        ),
        migrations.CreateModel(
            name='Substance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacokinetics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ROI', models.CharField(choices=[('Oral', 'Oral'), ('Insufflated', 'Insufflated'), ('Vaporized', 'Vaporized'), ('Rectal', 'Rectal'), ('Intravenous', 'Intravenous')], default='Oral', max_length=30)),
                ('bioavailability', models.FloatField()),
                ('tOnset', models.DurationField()),
                ('tMax', models.DurationField()),
                ('tHalf', models.DurationField()),
                ('substance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='substances.substance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DoseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ROI', models.CharField(choices=[('Oral', 'Oral'), ('Insufflated', 'Insufflated'), ('Vaporized', 'Vaporized'), ('Rectal', 'Rectal'), ('Intravenous', 'Intravenous')], default='Oral', max_length=30)),
                ('dosage', models.FloatField()),
                ('dosage_unit', models.CharField(choices=[('mg', 'mg')], default='mg', max_length=2)),
                ('timestamp', models.DateTimeField()),
                ('dosage_form', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='substances.dosageform')),
                ('substance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='substances.substance')),
            ],
            options={
                'verbose_name_plural': 'Dose Records',
                'db_table': 'dose_records',
            },
        ),
        migrations.CreateModel(
            name='DosageFormDose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.FloatField()),
                ('dosage_unit', models.CharField(choices=[('%', '%'), ('mg', 'mg')], default='%', max_length=2)),
                ('tOffset', models.DurationField(blank=True, null=True)),
                ('dosage_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='substances.dosageform')),
                ('substance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='substances.substance')),
            ],
            options={
                'verbose_name_plural': 'Dosage Form Doses',
                'db_table': 'dosage_form_doses',
            },
        ),
        migrations.AddField(
            model_name='dosageform',
            name='substance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='substances.substance'),
        ),
    ]
