# Generated by Django 4.0.6 on 2022-11-27 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('substances', '0002_dosageform_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pharmacokinetics',
            options={'verbose_name_plural': 'Pharmacokinetics'},
        ),
        migrations.RemoveField(
            model_name='dosageform',
            name='ROI',
        ),
    ]
