# Generated by Django 4.0.6 on 2022-11-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substances', '0003_alter_pharmacokinetics_options_remove_dosageform_roi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosageformdose',
            name='dosage',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='doserecord',
            name='ROI',
            field=models.CharField(choices=[('Oral', 'Oral'), ('Insufflated', 'Insufflated'), ('Vaporized', 'Vaporized'), ('Sublingual', 'Sublingual'), ('Rectal', 'Rectal'), ('Intravenous', 'Intravenous')], default='Oral', max_length=30),
        ),
        migrations.AlterField(
            model_name='doserecord',
            name='dosage',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pharmacokinetics',
            name='ROI',
            field=models.CharField(choices=[('Oral', 'Oral'), ('Insufflated', 'Insufflated'), ('Vaporized', 'Vaporized'), ('Sublingual', 'Sublingual'), ('Rectal', 'Rectal'), ('Intravenous', 'Intravenous')], default='Oral', max_length=30),
        ),
        migrations.AlterField(
            model_name='pharmacokinetics',
            name='bioavailability',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='pharmacokinetics',
            unique_together={('ROI', 'substance')},
        ),
    ]
