# Generated by Django 4.0.6 on 2022-12-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substances', '0005_substance_elimination_rate_constant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacokinetics',
            name='absorption_kinetics',
            field=models.CharField(blank=True, choices=[('Instantaneous', 'Instantaneous'), ('Zero Order', 'Zero Order'), ('First Order', 'First Order')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pharmacokinetics',
            name='absorption_rate_constant',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
