# Generated by Django 4.0.6 on 2022-12-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substances', '0006_pharmacokinetics_absorption_kinetics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacokinetics',
            name='tLag',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
