# Generated by Django 4.0.6 on 2022-12-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substances', '0007_pharmacokinetics_tlag'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosageformdose',
            name='tLag',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
